### ISSUE TITLE
Distribucion de trabajo en Gestionar Estados y periodos

### ISSUE THREAD

**Issue by bagonzalez** [bagonzalez/sidpla-minsal#9]
Hola Karen, por favor realizar aqui la distribucion del trabajo entre tu y yeny,  (crear Issue's) para que podamos ver el avance de cada quien. Saludos

**Comment by bagonzalez** [comment]
quisiera conocer el estado del avance de este Milestone ademas, quiero saber como se ha distribuido en tareas este caso

**Comment by KarenElviraPenate** [comment]
Mira ahora vamos a empezar con la Yeni, vamos a tratar de terminarlo nos vamos a reunir para trabajar y vamos a ver como lo repartimos, les avisamos a ver como quedamos y podran ver los cambio mas tarde. Mira una pregunta el de justificacion que la yeni lo ponga en el del censo o creamos otro. Mira yo considero que podemos crear otro y ponerlo junto con la infraestructura. Lo podemos llamar InfraestructuraBundle y ponerlo ahi me avisas.

**Comment by bagonzalez** [comment]
mira el de justificacion yo considero que seria mejor dejarlo en el PaoBundle, pienso que tiene mas relacion, porfa.
